### ISSUE TITLE
websites for inspiration

### ISSUE THREAD

**Issue by kennedy** [PossumHouseGames/possumhousegames.github.io#5]
We are currently using https://jekyllthemes.io/theme/minimal-mistakes as the current theme.

**Comment by Kpable** [comment]
So as a result of our website template search a week or two ago. 

Candidate templates

- http://jeromelachaud.com/grayscale-theme/
- https://forestryio.github.io/ubuild-jekyll/
- https://volny.github.io/creative-theme-jekyll/#
- https://ndrewtl.github.io/airspace-jekyll/ (<- We were leaning this one when last this was researched. Simple clean.)

References of either content/layout formatting and/or design

- https://hopoogames.com/
- https://nightschoolstudio.com/
- https://giantsquidstudios.com/
- https://moonlighterthegame.com/
- https://www.digitalsungames.com/

One of the biggest selling points of Possum House Games is Denny's pixel art so the thought was with these candidate templates to focus on that art.

**Comment by Kpable** [comment]
Most indie studio sites seem to share the same content

- A studio about section
- Games section
- Game pages
- Team Pages

With sub formatting of like game name, description, links to get/follow, trailer, features if applicable, screenshots and the like.
